[package]
name = "todd"
version = "0.1.0"
authors = ["Omar <omarrafat60@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
serde_json = { version = "1.0.140", features = ["preserve_order"] }
indexmap = "2.9.0"
